-- create table about_page (id bigint not null auto_increment, content varchar(255), is_enabled bit, name varchar(255), primary key (id)) engine=InnoDB;
-- create table commercial_development_level (commercial_project_id bigint not null, development_level_id bigint not null, note varchar(255), primary key (commercial_project_id, development_level_id)) engine=InnoDB;
-- create table commercial_project (advantage varchar(255), price varchar(255), process varchar(255), scope varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
-- create table commercial_transmission_method (commercial_project_id bigint not null, transmission_method_id bigint not null, note varchar(255), primary key (commercial_project_id, transmission_method_id)) engine=InnoDB;
-- create table contact (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), content varchar(255), email varchar(255), full_name varchar(255), is_replied bit, phone_number varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
-- create table customer_contact (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), content varchar(255), email varchar(255), full_name varchar(255), is_replied bit, phone_number varchar(255), project_id bigint, primary key (id)) engine=InnoDB;
-- create table development_level (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table domain (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table faq (id bigint not null auto_increment, answer varchar(255), question varchar(255), primary key (id)) engine=InnoDB;
-- create table field (id bigint not null, name varchar(255), child_of_field_id bigint, primary key (id)) engine=InnoDB;
-- create table functions (id bigint not null, code varchar(255), name varchar(255), role_id bigint, primary key (id)) engine=InnoDB;
-- create table group_detail (research_group_id bigint not null, role_of_group_id bigint not null, user_profile_id bigint not null, primary key (research_group_id, role_of_group_id, user_profile_id)) engine=InnoDB;
-- create table project (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), address varchar(255), author varchar(255), code varchar(255), company_name varchar(255), email varchar(255), fax varchar(255), is_highlighted bit, name varchar(255), phone_number varchar(255), project_image varchar(255), project_type varchar(255), ranking bigint, short_description varchar(255), template bigint, website varchar(255), approver_id bigint, status_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
-- create table project_field (field_id bigint not null, project_id bigint not null, primary key (field_id, project_id)) engine=InnoDB;
-- create table research_group (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), group_image varchar(255), group_name varchar(255), introduction varchar(255), publication varchar(255), research_topic varchar(255), short_description varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
-- create table researching_project (benefit varchar(255), challenge varchar(255), solution varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
-- create table role (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table role_of_group (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table status (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table transmisstion_method (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- create table user_function (function_id bigint not null, user_profile_id bigint not null, is_enabled bit, primary key (function_id, user_profile_id)) engine=InnoDB;
-- create table user_profile (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), address varchar(255), avatar varchar(255), bio varchar(255), dob date, email varchar(255), full_name varchar(255), gender integer, get_news bit, is_enabled bit, is_locked bit, password varchar(255), phone_number varchar(255), qualification varchar(255), username varchar(255), website varchar(255), domain_id bigint, role_id bigint, primary key (id)) engine=InnoDB;
-- alter table user_profile add constraint UK_9551piq2wp9kh4kket0wr65vt unique (username);
-- alter table commercial_development_level add constraint FK9hdikj82nwd529df5ct5129su foreign key (commercial_project_id) references commercial_project (id);
-- alter table commercial_development_level add constraint FK57lacbufuqc9rltnyo340vdfv foreign key (development_level_id) references development_level (id);
-- alter table commercial_project add constraint FKc21a85xmq5wd2sjjmj3yg1tsy foreign key (id) references project (id);
-- alter table commercial_transmission_method add constraint FK6pfbfjx1bb9qayjk7nui0isf3 foreign key (commercial_project_id) references commercial_project (id);
-- alter table commercial_transmission_method add constraint FK1sgri7kud0kmxyjjnjxujbscx foreign key (transmission_method_id) references transmisstion_method (id);
-- alter table customer_contact add constraint FK50urimuuxcv4cxgpwvfyo8536 foreign key (project_id) references project (id);
-- alter table field add constraint FK1bynjb8iw58x2gt01gualp00p foreign key (child_of_field_id) references field (id);
-- alter table functions add constraint FK3ln883697wxnlhotxq7i006yy foreign key (role_id) references role (id);
-- alter table group_detail add constraint FKnlon8yblw9fsca6t8035t6xik foreign key (research_group_id) references research_group (id);
-- alter table group_detail add constraint FKac88mwfoxr40chnyixsn2pys0 foreign key (role_of_group_id) references role_of_group (id);
-- alter table group_detail add constraint FK94ic1vejr6wcfxim7r832t8uj foreign key (user_profile_id) references user_profile (id);
-- alter table project add constraint FK7ai3sryd5mvis1i3uqhpytmc8 foreign key (approver_id) references user_profile (id);
-- alter table project add constraint FKiwo74yc7wlfnk1t8m5rup6cao foreign key (status_id) references status (id);
-- alter table project add constraint FKj7tkcpv3aln1ufnui1e91pwyp foreign key (user_id) references user_profile (id);
-- alter table project_field add constraint FKau15libp6x60uwa50w5bfcpum foreign key (field_id) references field (id);
-- alter table project_field add constraint FKf78597jcwnmr6jtofgn0oham0 foreign key (project_id) references project (id);
-- alter table research_group add constraint FK9pyn44pj1kpep4r7vrb0s69if foreign key (user_id) references user_profile (id);
-- alter table researching_project add constraint FKg3vqrmve0qxeks83lj1ahcbkv foreign key (id) references project (id);
-- alter table user_function add constraint FKswv7hh9fhjo26fyh4oas0bxke foreign key (function_id) references functions (id);
-- alter table user_function add constraint FKoqye0efgipq16w8xhleup3r1d foreign key (user_profile_id) references user_profile (id);
-- alter table user_profile add constraint FKjqe2wh2gtvuo7n85n2jvxhfb7 foreign key (domain_id) references domain (id);
-- alter table user_profile add constraint FK93vvtknbpduxlei8xo33hwp02 foreign key (role_id) references role (id);
-- create table footer (id bigint not null auto_increment, content varchar(255), primary key (id)) engine=InnoDB;
-- create table idea_project (description varchar(255), scope varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
-- alter table idea_project add constraint FKcfjlm8oudwxy166c0rjcjcchv foreign key (id) references project (id);
-- create table transmission_method (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
-- alter table commercial_transmission_method add constraint FK1w0ocogvtgr6ivyx4j3j5vkxb foreign key (transmission_method_id) references transmission_method (id);
-- alter table functions add column url varchar(255);
create table about_page (id bigint not null, content varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table commercial_development_level (commercial_project_id bigint not null, development_level_id bigint not null, note varchar(255), primary key (commercial_project_id, development_level_id)) engine=InnoDB;
create table commercial_project (advantage varchar(255), price varchar(255), process varchar(255), scope varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
create table commercial_transmission_method (commercial_project_id bigint not null, transmission_method_id bigint not null, note varchar(255), primary key (commercial_project_id, transmission_method_id)) engine=InnoDB;
create table contact (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), content varchar(255), email varchar(255), full_name varchar(255), is_replied bit, phone_number varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table customer_contact (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), content varchar(255), email varchar(255), full_name varchar(255), is_replied bit, phone_number varchar(255), project_id bigint, primary key (id)) engine=InnoDB;
create table development_level (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table domain (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table faq (id bigint not null auto_increment, answer varchar(255), question varchar(255), primary key (id)) engine=InnoDB;
create table field (id bigint not null, name varchar(255), child_of_field_id bigint, primary key (id)) engine=InnoDB;
create table footer (id bigint not null, content varchar(255), primary key (id)) engine=InnoDB;
create table functions (id bigint not null, code varchar(255), name varchar(255), url varchar(255), role_id bigint, primary key (id)) engine=InnoDB;
create table group_detail (id bigint not null auto_increment, avatar varchar(255), bio varchar(255), email varchar(255), full_name varchar(255), qualification varchar(255), website varchar(255), research_group_id bigint, role_of_group_id bigint, user_profile_id bigint, primary key (id)) engine=InnoDB;
create table idea_project (description varchar(255), scope varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
create table password_reset_code (id bigint not null auto_increment, expiry_date datetime(6), reset_code varchar(255), primary key (id)) engine=InnoDB;
create table project (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), address varchar(255), author varchar(255), company_name varchar(255), email varchar(255), fax varchar(255), is_highlighted bit, name varchar(255), phone_number varchar(255), project_image varchar(255), project_type varchar(255), ranking bigint, short_description varchar(255), template bigint, website varchar(255), approver_id bigint, status_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table project_field (field_id bigint not null, project_id bigint not null, primary key (field_id, project_id)) engine=InnoDB;
create table research_group (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), group_image varchar(255), group_name varchar(255), introduction varchar(255), publication varchar(255), research_topic varchar(255), short_description varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table researching_project (benefit varchar(255), challenge varchar(255), solution varchar(255), id bigint not null, primary key (id)) engine=InnoDB;
create table role (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table role_of_group (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table status (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table transmission_method (id bigint not null, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table user_function (function_id bigint not null, user_profile_id bigint not null, is_enabled bit, primary key (function_id, user_profile_id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, created_date datetime(6), is_deleted bit, updated_date datetime(6), address varchar(255), avatar varchar(255), bio varchar(255), dob date, email varchar(255), full_name varchar(255), gender integer, get_news bit, is_enabled bit, is_locked bit, password varchar(255), phone_number varchar(255), qualification varchar(255), username varchar(255), website varchar(255), domain_id bigint, password_reset_code_id bigint, role_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK_9551piq2wp9kh4kket0wr65vt unique (username);
alter table commercial_development_level add constraint FK9hdikj82nwd529df5ct5129su foreign key (commercial_project_id) references commercial_project (id);
alter table commercial_development_level add constraint FK57lacbufuqc9rltnyo340vdfv foreign key (development_level_id) references development_level (id);
alter table commercial_project add constraint FKc21a85xmq5wd2sjjmj3yg1tsy foreign key (id) references project (id);
alter table commercial_transmission_method add constraint FK6pfbfjx1bb9qayjk7nui0isf3 foreign key (commercial_project_id) references commercial_project (id);
alter table commercial_transmission_method add constraint FK1w0ocogvtgr6ivyx4j3j5vkxb foreign key (transmission_method_id) references transmission_method (id);
alter table customer_contact add constraint FK50urimuuxcv4cxgpwvfyo8536 foreign key (project_id) references project (id);
alter table field add constraint FK1bynjb8iw58x2gt01gualp00p foreign key (child_of_field_id) references field (id);
alter table functions add constraint FK3ln883697wxnlhotxq7i006yy foreign key (role_id) references role (id);
alter table group_detail add constraint FKnlon8yblw9fsca6t8035t6xik foreign key (research_group_id) references research_group (id);
alter table group_detail add constraint FKac88mwfoxr40chnyixsn2pys0 foreign key (role_of_group_id) references role_of_group (id);
alter table group_detail add constraint FK94ic1vejr6wcfxim7r832t8uj foreign key (user_profile_id) references user_profile (id);
alter table idea_project add constraint FKcfjlm8oudwxy166c0rjcjcchv foreign key (id) references project (id);
alter table project add constraint FK7ai3sryd5mvis1i3uqhpytmc8 foreign key (approver_id) references user_profile (id);
alter table project add constraint FKiwo74yc7wlfnk1t8m5rup6cao foreign key (status_id) references status (id);
alter table project add constraint FKj7tkcpv3aln1ufnui1e91pwyp foreign key (user_id) references user_profile (id);
alter table project_field add constraint FKau15libp6x60uwa50w5bfcpum foreign key (field_id) references field (id);
alter table project_field add constraint FKf78597jcwnmr6jtofgn0oham0 foreign key (project_id) references project (id);
alter table research_group add constraint FK9pyn44pj1kpep4r7vrb0s69if foreign key (user_id) references user_profile (id);
alter table researching_project add constraint FKg3vqrmve0qxeks83lj1ahcbkv foreign key (id) references project (id);
alter table user_function add constraint FKswv7hh9fhjo26fyh4oas0bxke foreign key (function_id) references functions (id);
alter table user_function add constraint FKoqye0efgipq16w8xhleup3r1d foreign key (user_profile_id) references user_profile (id);
alter table user_profile add constraint FKjqe2wh2gtvuo7n85n2jvxhfb7 foreign key (domain_id) references domain (id);
alter table user_profile add constraint FKah5v987xsq46tapdnpod83acg foreign key (password_reset_code_id) references password_reset_code (id);
alter table user_profile add constraint FK93vvtknbpduxlei8xo33hwp02 foreign key (role_id) references role (id);
